-- Add price and stock columns to products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS prix_15ml DECIMAL(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_15ml INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS prix_30ml DECIMAL(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_30ml INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS prix_50ml DECIMAL(10,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_50ml INTEGER DEFAULT 0;
