name: Supabase Auto Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  plan:  # vérifie les PR (ne modifie rien)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Dry-run
        run: |
          set -e
          supabase db push \
            --db-url "${SUPABASE_DB_URL}" \
            --workdir ./supabase \
            --dry-run

  sync:  # applique en prod après merge/push/manuel
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Push schema/migrations (idempotent)
        run: |
          set -e
          supabase db push \
            --db-url "${SUPABASE_DB_URL}" \
            --workdir ./supabase \
            --include-all \
            --yes
