name: Supabase Migrations
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      # On pousse les migrations directement sur la DB via l'URL sécurisée
      - name: Apply migrations
        run: supabase db push --db-url "${{ secrets.SUPABASE_DB_URL }}"
