name: Supabase Migrations

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Afficher version CLI
        run: supabase --version

      - name: Lier projet (optionnel mais sûr)
        run: |
          set -e
          REF_FROM_URL="$(echo "${{ secrets.SUPABASE_DB_URL }}" | sed -E 's#.*postgresql://postgres\.([^:]+):.*#\1#')"
          echo "Ref détecté: $REF_FROM_URL"
          supabase link --project-ref "$REF_FROM_URL" --workdir ./supabase || true

      - name: Pousser les migrations (idempotent)
        run: |
          set -e
          # Utilise le POOLER (SUPABASE_DB_URL)
          supabase db push             --workdir ./supabase             --db-url "${SUPABASE_DB_URL}"             --non-interactive             --debug

