name: Supabase Auto Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard:"DB changée => migration requise"
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        run: |
          set -e
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="origin/${{ github.base_ref }}...${{ github.sha }}"
          else
            RANGE="${{ github.event.before }}...${{ github.sha }}"
          fi
          echo "Diff range: $RANGE"
          CHANGED="$(git diff --name-only $RANGE || true)"
          echo "$CHANGED" | sed 's/^/ - /'

          CHANGED_DB="$(echo "$CHANGED" | grep -E '^supabase/' | grep -vE '^supabase/migrations/' || true)"
          HAS_MIG="$(echo "$CHANGED" | grep -E '^supabase/migrations/.*\\.sql$' || true)"

          if [ -n "$CHANGED_DB" ] && [ -z "$HAS_MIG" ]; then
            echo '❌ Des fichiers DB ont changé sans migration SQL (supabase/migrations/*.sql).'
            exit 1
          fi
          echo '✅ Garde-fou OK : aucune infraction.'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Dry-run
        run: |
          set -e
          supabase db push \
            --db-url "${SUPABASE_DB_URL}" \
            --workdir ./supabase \
            --dry-run

  sync:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard:"DB changée => migration requise"
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
        run: |
          set -e
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="origin/${{ github.base_ref }}...${{ github.sha }}"
          else
            RANGE="${{ github.event.before }}...${{ github.sha }}"
          fi
          echo "Diff range: $RANGE"
          CHANGED="$(git diff --name-only $RANGE || true)"
          echo "$CHANGED" | sed 's/^/ - /'

          CHANGED_DB="$(echo "$CHANGED" | grep -E '^supabase/' | grep -vE '^supabase/migrations/' || true)"
          HAS_MIG="$(echo "$CHANGED" | grep -E '^supabase/migrations/.*\\.sql$' || true)"

          if [ -n "$CHANGED_DB" ] && [ -z "$HAS_MIG" ]; then
            echo '❌ Des fichiers DB ont changé sans migration SQL (supabase/migrations/*.sql).'
            exit 1
          fi
          echo '✅ Garde-fou OK : aucune infraction.'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Push schema/migrations (idempotent)
        run: |
          set -e
          supabase db push \
            --db-url "${SUPABASE_DB_URL}" \
            --workdir ./supabase \
            --include-all \
            --yes
