name: Supabase Migrations

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/**"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Apply migrations (non-interactive)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          supabase db push --db-url "$SUPABASE_DB_URL" --non-interactive
