name: Supabase Auto Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  plan:
    name: plan 
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Dry-run (no DB change)
        run: |
          supabase db push \
            --workdir ./supabase \
            --db-url "${SUPABASE_DB_URL}" \
            --dry-run

  sync:
    name: sync
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_URL:      ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: supabase/setup-cli@v1
        with: { version: latest }
      - name: Apply migrations (idempotent)
        run: |
          supabase db push \
            --db-url "${SUPABASE_DB_URL}" \
            --workdir ./supabase \
            --include-all \
            --yes
